behaviors:
  NupjukJump:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3e-4
      beta: 0.02
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.01
        network_settings:
          hidden_units: 64
        learning_rate: 3e-4
    max_steps: 5e7
    time_horizon: 64
    summary_freq: 10000